#!/usr/bin/env python3

import sys
import os
import gzip
import json
import pyterrier as pt
from tqdm import tqdm


def _d2q_iter():
    with gzip.open('data/d2q.jsonl.gz') as f:
        for l in f:
            yield json.loads(l)


if '__main__' == __name__:
    ds = pt.get_dataset('irds:msmarco-passage')
    for doc, queries in tqdm(zip(ds.get_corpus_iter(verbose=False), _d2q_iter())):
        assert doc['docno'] == queries['id']
        docid = doc['docno']
        body = doc['text']
        qry_text = ' '.join(queries['predicted_queries'])
        print(f'{docid}\t{body} {qry_text}')
